import * as THREE from 'three';

const SIZE  = 512; // texture resolution for both preview and sampling
const THUMB = 80;

// ── Helpers ──────────────────────────────────────────────────────────────────

function makeCanvas(w, h = w) {
  const c = document.createElement('canvas');
  c.width  = w;
  c.height = h;
  return c;
}

/** Return { w, h } capped at SIZE on the longest side, preserving aspect ratio. */
function fitDimensions(imgW, imgH) {
  const scale = Math.min(SIZE / imgW, SIZE / imgH, 1);
  return { w: Math.round(imgW * scale), h: Math.round(imgH * scale) };
}

// ── Manifest-driven preset loading ────────────────────────────────────────────

/**
 * Fetch the manifest generated by generate_manifest.py.
 * Returns { categories: [ { id, label, textures: [...] } ] }
 */
export async function fetchManifest() {
  const resp = await fetch('textures/manifest.json');
  if (!resp.ok) throw new Error(`Failed to load manifest: ${resp.status}`);
  return resp.json();
}

/**
 * Flatten manifest categories into IMAGE_PRESETS-style array.
 * Each entry gets: { name, url, thumb, defaultScale, category }
 */
export function flattenManifest(manifest) {
  const presets = [];
  for (const cat of manifest.categories) {
    for (const tex of cat.textures) {
      presets.push({
        name:         tex.name,
        url:          `textures/${cat.label}/${tex.file}`,
        thumb:        `textures/${cat.label}/${tex.thumb}`,
        defaultScale: tex.defaultScale ?? 0.5,
        category:     cat.id,
      });
    }
  }
  return presets;
}

/**
 * Extract unique categories from manifest, adding an "All" entry at the front.
 */
export function extractCategories(manifest) {
  const cats = [{ id: 'all', label: 'All' }];
  for (const cat of manifest.categories) {
    cats.push({ id: cat.id, label: cat.label });
  }
  return cats;
}

// ── Cache ─────────────────────────────────────────────────────────────────────
const _fullPresetCache = new Map();

/**
 * Load only the pre-computed thumbnail for a preset.
 * Returns { name, thumbCanvas, defaultScale }.
 */
export function loadPresetThumbnail(preset) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const thumb = makeCanvas(THUMB);
      thumb.getContext('2d').drawImage(img, 0, 0, THUMB, THUMB);
      resolve({ name: preset.name, thumbCanvas: thumb, defaultScale: preset.defaultScale });
    };
    img.onerror = () => reject(new Error(`Failed to load thumbnail: ${preset.thumb}`));
    img.src = preset.thumb;
  });
}

/**
 * Load all thumbnails from a flat preset array.
 * Returns Promise<Array<{ name, thumbCanvas, defaultScale }|null>>.
 */
export function loadAllThumbnails(presets) {
  return Promise.all(presets.map(p =>
    loadPresetThumbnail(p).catch(() => null)
  ));
}

/**
 * Load full-resolution texture for a preset (on demand).
 * Results are cached so repeated calls return instantly.
 */
export function loadFullPreset(idx, presets) {
  if (_fullPresetCache.has(idx)) return Promise.resolve(_fullPresetCache.get(idx));
  const preset = presets[idx];
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const { w, h } = fitDimensions(img.width, img.height);
      const full = makeCanvas(w, h);
      full.getContext('2d').drawImage(img, 0, 0, w, h);

      const imageData = full.getContext('2d').getImageData(0, 0, w, h);
      const texture   = new THREE.CanvasTexture(full);
      texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
      texture.name = preset.name;

      const entry = { name: preset.name, fullCanvas: full, texture, imageData, width: w, height: h, defaultScale: preset.defaultScale };
      _fullPresetCache.set(idx, entry);
      resolve(entry);
    };
    img.onerror = () => reject(new Error(`Failed to load preset image: ${preset.url}`));
    img.src = preset.url;
  });
}


/**
 * Build a THREE.CanvasTexture + ImageData from a user-uploaded image File.
 */
export function loadCustomTexture(file) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    const url = URL.createObjectURL(file);
    img.onload = () => {
      URL.revokeObjectURL(url);
      const { w, h } = fitDimensions(img.width, img.height);
      const canvas = makeCanvas(w, h);
      const ctx    = canvas.getContext('2d');
      ctx.drawImage(img, 0, 0, w, h);
      const imageData = ctx.getImageData(0, 0, w, h);
      const texture   = new THREE.CanvasTexture(canvas);
      texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
      texture.name = file.name;
      resolve({ name: file.name, fullCanvas: canvas, texture, imageData, width: w, height: h });
    };
    img.onerror = () => { URL.revokeObjectURL(url); reject(new Error('Failed to load image')); };
    img.src = url;
  });
}
